[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/expenses"
  to = "/expenses.html"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/profile.html"
  status = 200

[[redirects]]
  from = "/upload-ticket"
  to = "/upload-ticket.html"
  status = 200

[[redirects]]
  from = "/advisor"
  to = "/advisor.html"
  status = 200
